### ISSUE TITLE
On starting the app with Kafka

### ISSUE THREAD

**Issue by phoenix303** [sanjuthomas/kafka-connect-marklogic#14]
On starting the app with Kafka, it is throwing the below errors:

[2018-05-30 16:13:46,276] INFO [Consumer clientId=consumer-8, groupId=connect-marklogic-sink] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:411)
[2018-05-30 16:13:46,276] INFO [Consumer clientId=consumer-8, groupId=connect-marklogic-sink] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:442)
[2018-05-30 16:13:46,276] INFO [Consumer clientId=consumer-9, groupId=connect-marklogic-sink] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:411)
[2018-05-30 16:13:46,279] INFO [Consumer clientId=consumer-9, groupId=connect-marklogic-sink] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:442)
[2018-05-30 16:13:46,289] INFO [Consumer clientId=consumer-8, groupId=connect-marklogic-sink] Successfully joined group with generation 23 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:409)
[2018-05-30 16:13:46,290] INFO [Consumer clientId=consumer-9, groupId=connect-marklogic-sink] Successfully joined group with generation 23 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:409)
[2018-05-30 16:13:46,290] INFO [Consumer clientId=consumer-9, groupId=connect-marklogic-sink] Setting newly assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:256)
[2018-05-30 16:13:46,290] INFO [Consumer clientId=consumer-8, groupId=connect-marklogic-sink] Setting newly assigned partitions [quote-request-0] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:256)
[2018-05-30 16:13:46,298] INFO [Consumer clientId=consumer-8, groupId=connect-marklogic-sink] Resetting offset for partition quote-request-0 to offset 0. (org.apache.kafka.clients.consumer.internals.Fetcher:561)
[2018-05-30 16:13:46,303] INFO Received 1 records. kafka coordinates from record: Topic - quote-request, Partition - 0, Offset - 0 (kafka.connect.marklogic.sink.MarkLogicSinkTask:43)
[2018-05-30 16:13:46,310] INFO (withForestConfig) Using [localhost] hosts with forests for "Documents" (com.marklogic.client.datamovement.impl.WriteBatcherImpl:745)
[2018-05-30 16:13:46,310] INFO Adding DatabaseClient on port 8000 for host "localhost" to the rotation (com.marklogic.client.datamovement.impl.WriteBatcherImpl:759)
[2018-05-30 16:13:46,311] INFO threadCount=8 (com.marklogic.client.datamovement.impl.WriteBatcherImpl:259)
[2018-05-30 16:13:46,311] INFO batchSize=100 (com.marklogic.client.datamovement.impl.WriteBatcherImpl:260)
[2018-05-30 16:13:46,311] ERROR WorkerSinkTask{id=marklogic-sink-7} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:544)
java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:501)
	at java.util.LinkedHashMap.<init>(LinkedHashMap.java:384)
	at kafka.connect.marklogic.MarkLogicBufferedWriter.lambda$flush$2(MarkLogicBufferedWriter.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at kafka.connect.marklogic.MarkLogicBufferedWriter.flush(MarkLogicBufferedWriter.java:73)
	at kafka.connect.marklogic.MarkLogicBufferedWriter.write(MarkLogicBufferedWriter.java:59)
	at kafka.connect.marklogic.sink.MarkLogicSinkTask.put(MarkLogicSinkTask.java:47)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-30 16:13:46,311] INFO Flush - Topic quote-request, Partition 0, Offset 0, Metadata  (kafka.connect.marklogic.sink.MarkLogicSinkTask:100)
[2018-05-30 16:13:46,312] ERROR WorkerSinkTask{id=marklogic-sink-7} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.util.HashMap.putMapEntries(HashMap.java:501)
	at java.util.LinkedHashMap.<init>(LinkedHashMap.java:384)
	at kafka.connect.marklogic.MarkLogicBufferedWriter.lambda$flush$2(MarkLogicBufferedWriter.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at kafka.connect.marklogic.MarkLogicBufferedWriter.flush(MarkLogicBufferedWriter.java:73)
	at kafka.connect.marklogic.MarkLogicBufferedWriter.write(MarkLogicBufferedWriter.java:59)
	at kafka.connect.marklogic.sink.MarkLogicSinkTask.put(MarkLogicSinkTask.java:47)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)

**Comment by phoenix303** [comment]
I was able to resolve this issue.
